[project]
name = "summary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.28.0",
    "kokkai-db",
    "sqlalchemy>=2.0.42",
]

[tool.uv.sources]
kokkai-db = { path = "../db" }
