services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:8000"
    links:
      - db
    develop:
      watch:
        - action: sync
          path: api
          target: /app/api
          ignore:
            - __pycache__
            - Dockerfile
        - action: sync
          path: db
          target: /app/db
          ignore:
            - __pycache__
            - Dockerfile
        - action: rebuild
          path: api/Dockerfile
    

volumes:
  db_data:
