services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:8000"
    secrets:
      - database_url
    depends_on:
      - db
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: api
          target: /app/api
          ignore:
            - __pycache__
            - Dockerfile
        - action: sync
          path: db
          target: /app/db
          ignore:
            - __pycache__
            - Dockerfile
        - action: rebuild
          path: api/Dockerfile

  summary:
    build:
      context: .
      dockerfile: summary/Dockerfile
    secrets:
      - database_url
      - gemini_api_key
    depends_on:
      - db
    restart: on-failure
    develop:
      watch:
        - action: sync+restart
          path: summary
          target: /app/summary
          ignore:
            - __pycache__
            - Dockerfile
            - cronjob
        - action: sync+restart
          path: db
          target: /app/db
          ignore:
            - __pycache__
            - Dockerfile
        - action: sync+exec
          path: summary/cronjob
          target: /etc/cron.d/summary-cron
          exec:
            command: cron -f
        - action: rebuild
          path: summary/Dockerfile
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    develop:
      watch:
        - path: web
          action: rebuild

volumes:
  db_data:

secrets:
  database_url:
    file: ./secrets/database_url
  gemini_api_key:
    file: ./secrets/gemini_api_key
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  postgres_db:
    file: ./secrets/postgres_db