services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:8000"
    links:
      - db
    develop:
      watch:
        - action: sync
          path: api
          target: /app/api
          ignore:
            - __pycache__
            - Dockerfile
        - action: sync
          path: db
          target: /app/db
          ignore:
            - __pycache__
            - Dockerfile
        - action: rebuild
          path: api/Dockerfile

  summary:
    build:
      context: .
      dockerfile: summary/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GEMINI_API_KEY: $GEMINI_API_KEY
    links:
      - db
    depends_on:
      - db
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: summary
          target: /app/summary
          ignore:
            - __pycache__
            - Dockerfile
            - cronjob
        - action: sync
          path: db
          target: /app/db
          ignore:
            - __pycache__
            - Dockerfile
        - action: sync+exec
          path: summary/cronjob
          target: /etc/cron.d/summary-cron
          exec:
            command: cron -f
        - action: rebuild
          path: summary/Dockerfile

volumes:
  db_data:
