"""v3_fix_datetime_column

Revision ID: 2401244fb033
Revises: afd1d1b644bc
Create Date: 2025-08-08 23:28:26.137196

"""
from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '2401244fb033'
down_revision: Union[str, Sequence[str], None] = 'afd1d1b644bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 既存のsummariesテーブルのレコードにcreate_time, update_timeを設定
    now = datetime.now()
    op.execute(
        text("""
        UPDATE summaries
        SET
            create_time = COALESCE(NULLIF(create_time, '')::TIMESTAMP WITHOUT TIME ZONE, :now),
            update_time = COALESCE(NULLIF(update_time, '')::TIMESTAMP WITHOUT TIME ZONE, :now)
        WHERE create_time IS NULL OR create_time = '' OR update_time IS NULL OR update_time = '';
        """).bindparams(now=now)
    )

    op.alter_column('speeches', 'create_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="create_time::timestamp without time zone")
    op.alter_column('speeches', 'update_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="update_time::timestamp without time zone")
    op.alter_column('summaries', 'create_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False,
               postgresql_using="create_time::timestamp without time zone")
    op.alter_column('summaries', 'update_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False,
               postgresql_using="update_time::timestamp without time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summaries', 'update_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('summaries', 'create_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('speeches', 'update_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('speeches', 'create_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###