"""add prompt_version to summaries

Revision ID: b645a1f2546b
Revises: 2401244fb033
Create Date: 2025-08-11 10:28:26.543823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b645a1f2546b'
down_revision: Union[str, Sequence[str], None] = '2401244fb033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('prompt_version', sa.Integer(), nullable=False, server_default='1'))
    op.drop_constraint('summaries_pkey', 'summaries', type_='primary')
    op.create_primary_key('summaries_pkey', 'summaries', ['issue_id', 'model', 'prompt_version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('summaries_pkey', 'summaries', type_='primary')
    op.create_primary_key('summaries_pkey', 'summaries', ['issue_id', 'model'])
    op.drop_column('summaries', 'prompt_version')
    # ### end Alembic commands ###