"""v1-first-creation

Revision ID: c8394d8c4db0
Revises:
Create Date: 2025-08-06 11:15:31.641326

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8394d8c4db0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("image_kind", sa.String(), nullable=False),
        sa.Column("search_object", sa.Integer(), nullable=False),
        sa.Column("session", sa.Integer(), nullable=False),
        sa.Column("name_of_house", sa.String(), nullable=False),
        sa.Column("name_of_meeting", sa.String(), nullable=True),
        sa.Column("issue", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("closing", sa.String(), nullable=True),
        sa.Column("meeting_url", sa.String(), nullable=False),
        sa.Column("pdf_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("issue_id"),
        sa.UniqueConstraint("issue_id"),
    )
    op.create_table(
        "speeches",
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("speech_id", sa.String(), nullable=False),
        sa.Column("speech_order", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(), nullable=True),
        sa.Column("speaker_yomi", sa.String(), nullable=True),
        sa.Column("speaker_group", sa.String(), nullable=True),
        sa.Column("speaker_position", sa.String(), nullable=True),
        sa.Column("speaker_role", sa.String(), nullable=True),
        sa.Column("speech", sa.Text(), nullable=True),
        sa.Column("start_page", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.String(), nullable=True),
        sa.Column("update_time", sa.String(), nullable=True),
        sa.Column("speech_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["meetings.issue_id"],
        ),
        sa.PrimaryKeyConstraint("speech_id"),
        sa.UniqueConstraint("speech_id"),
    )
    op.create_table(
        "summaries",
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("create_time", sa.String(), nullable=True),
        sa.Column("update_time", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["meetings.issue_id"],
        ),
        sa.PrimaryKeyConstraint("issue_id", "model"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summaries")
    op.drop_table("speeches")
    op.drop_table("meetings")
    # ### end Alembic commands ###
