import { useParams, Link } from "react-router";
import ReactMarkdown from "react-markdown";
import { useState, useEffect } from "react"; // 追加
import { graphqlRequest } from "~/lib/api"; // 追加

// Define types for our data based on the API schema
interface Meeting {
	issueId: string;
	session: number;
	nameOfHouse: string;
	nameOfMeeting: string;
	issue: string;
	date: string;
	summary: {
		summary: string;
		model: string;
	} | null;
}

// GraphQL Query (文字列として定義)
const GET_MEETING_DETAILS_QUERY = `
  query GetMeetingDetails($issueId: String!) {
    meetings(issueId: $issueId) {
      issueId
      session
      nameOfHouse
      nameOfMeeting
      issue
      date
      summary {
        summary
        model
      }
    }
  }
`;

export default function SummaryPage() {
	const { issueId } = useParams<{ issueId: string }>();
	const [meeting, setMeeting] = useState<Meeting | null>(null); // meeting ステートを追加
	const [loading, setLoading] = useState(true); // loading ステートを追加
	const [error, setError] = useState<string | null>(null); // error ステートを追加

	useEffect(() => {
		const fetchMeetingDetails = async () => {
			if (!issueId) {
				setLoading(false);
				setError("Issue ID is missing.");
				return;
			}
			setLoading(true);
			setError(null);
			try {
				const data = await graphqlRequest<{ meetings: Meeting[] }>(
					GET_MEETING_DETAILS_QUERY,
					{ issueId },
				);
				setMeeting(
					data.meetings && data.meetings.length > 0 ? data.meetings[0] : null,
				);
			} catch (err: unknown) {
				console.error("Error loading summary:", err);
				if (err instanceof Error) {
					setError(err.message || "Failed to load summary.");
				} else {
					setError("Failed to load summary.");
				}
			} finally {
				setLoading(false);
			}
		};
		fetchMeetingDetails();
	}, [issueId]);

	if (loading) {
		return <div className="p-4">Loading...</div>;
	}

	if (error) {
		return <div className="p-4">Error loading summary: {error}</div>;
	}

	if (!meeting) {
		return <div className="p-4">Meeting not found.</div>;
	}

	return (
		<div className="p-4 bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 min-h-screen">
			<Link
				to="/"
				className="text-blue-600 hover:underline mb-4 block dark:text-blue-400"
			>
				&larr; Back to Search
			</Link>
			<h1 className="text-3xl font-bold">{meeting.nameOfMeeting}</h1>
			<p className="text-lg text-gray-700 dark:text-gray-300">
				{meeting.issue}
			</p>
			<p className="text-md text-gray-500 mb-4 dark:text-gray-400">
				{meeting.nameOfHouse} - {new Date(meeting.date).toLocaleDateString()}
			</p>

			<div className="prose lg:prose-xl max-w-none dark:prose-invert">
				{meeting.summary ? (
					<ReactMarkdown>{meeting.summary.summary}</ReactMarkdown>
				) : (
					<p>No summary available for this meeting.</p>
				)}
			</div>
			{meeting.summary && (
				<p className="text-sm text-gray-500 mt-4 dark:text-gray-400">
					Summary generated by: {meeting.summary.model}
				</p>
			)}
		</div>
	);
}
